# Generated by Django 5.2.17 on 2026-09-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_oauth_apikey_onboarding'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apikey',
            new_name='accounts_ap_prefix_500cff_idx',
            old_name='accounts_ap_prefix_3d2c46_idx',
        ),
    ]
