# Generated by Django 5.2.17 on 2026-09-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_accounts_ap_prefix_3d2c46_idx_accounts_ap_prefix_500cff_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_narration_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
