# Generated by Django 5.2.17 on 2026-09-20 19:15

import common.crypto
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alertchannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertchannel',
            name='config_encrypted',
            field=common.crypto.EncryptedTextField(blank=True, default=''),
        ),
    ]
