# Generated by Django 5.2.17 on 2026-09-21 06:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0004_workspace_and_intervals'),
        ('notifications', '0004_alter_alertchannel_config_encrypted'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorAlertChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_routes', to='notifications.alertchannel')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_routes', to='monitors.monitor')),
            ],
            options={
                'indexes': [models.Index(fields=['monitor'], name='notificatio_monitor_adbff5_idx'), models.Index(fields=['channel'], name='notificatio_channel_d89da9_idx')],
                'constraints': [models.UniqueConstraint(fields=('monitor', 'channel'), name='unique_monitor_channel')],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(default='', max_length=20)),
                ('event_type', models.CharField(default='', max_length=20)),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('detail', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='notifications.alertchannel')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notificationevent')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to='monitors.monitor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['monitor', '-created_at'], name='notificatio_monitor_e2d317_idx'), models.Index(fields=['channel', '-created_at'], name='notificatio_channel_ed9dd5_idx')],
            },
        ),
    ]
