# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_monitoralertchannel_notificationdelivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="email_weekly_digest",
            field=models.BooleanField(default=True),
        ),
    ]
