import Link from "next/link";

import { LegalPage, LegalSection, ReviewNote } from "@/components/marketing/legal-page";
import { marketingMetadata } from "@/lib/marketing-seo";

export const metadata = marketingMetadata({
  title: "Privacy Policy",
  description:
    "How the current Sitemyra application handles account, monitoring, notification, and billing data.",
  path: "/privacy",
});

export default function PrivacyPage() {
  return (
    <LegalPage
      eyebrow="Legal"
      title="Privacy Policy"
      description="A plain-language description of the data handled by the current Sitemyra application. It is written from the implementation in this repository and should be reviewed again when the business setup or providers change."
    >
      <ReviewNote>
        Sitemyra is currently an independent project. The legal operator name,
        business registration details, VAT information, invoicing process,
        governing law, refund policy, and final provider list still need to be
        verified by the founder before paid subscriptions are accepted.
      </ReviewNote>

      <LegalSection title="1. Who this policy covers">
        <p>
          This policy describes the Sitemyra web application and dashboard. It
          covers information processed when you create an account, configure a
          monitor, receive an alert, use billing features, or contact the
          project. Sitemyra is an independent SaaS project built in Greece by
          Konstantinos Gkogkos.
        </p>
        <p>
          The application may be operated through infrastructure providers whose
          details are not recorded in this repository. Those providers may
          process technical connection information under their own terms. The
          operator should add the verified hosting provider and relevant
          business details before treating this page as a final legal notice.
        </p>
      </LegalSection>

      <LegalSection title="2. Information you provide">
        <ul>
          <li>
            <strong>Account information:</strong> your email address, account
            creation and update timestamps, and account status.
          </li>
          <li>
            <strong>Authentication information:</strong> your password is
            processed by Django&apos;s password hashing system. If you use a
            configured Google or GitHub sign-in provider, the provider
            identifier and verified email information may also be stored.
          </li>
          <li>
            <strong>Monitoring choices:</strong> the name and URL of each
            monitor, active or paused state, check interval, timeout, and any
            selected monitoring mode or CSS selector.
          </li>
          <li>
            <strong>Notification choices:</strong> email preferences and the
            names, types, and encrypted destinations of channels you configure.
          </li>
          <li>
            <strong>Support or contact details:</strong> information you choose
            to send to the founder by email or through a public founder link.
          </li>
        </ul>
      </LegalSection>

      <LegalSection title="3. Information generated by monitoring">
        <p>
          When a monitor runs, Sitemyra may process the target page&apos;s
          response, status code, response time, content hash, error details,
          selected price values, DOM content, screenshots, and change
          information. It may also store a monitor history, a price point, a
          change diff, and an artifact such as an HTML or image file.
        </p>
        <p>
          Monitoring is intended for public pages that you are authorized to
          access. Sitemyra does not bypass login walls, access controls, or
          website terms. The HTTP fetch layer identifies itself as
          <code> SitemyraMonitor/1.0</code>; browser-based checks use the
          browser&apos;s normal request identity. Both paths block a set of
          unsafe network destinations.
        </p>
      </LegalSection>

      <LegalSection title="4. Why the information is used">
        <p>
          The information is used to create and secure accounts, schedule and
          perform checks, show monitor history, deliver requested notifications,
          provide billing and customer-support functions, prevent abuse, and
          maintain the reliability of the service.
        </p>
        <p>
          Where data-protection law applies, the operator should document the
          appropriate legal basis for each processing purpose. This page is a
          product description, not legal advice.
        </p>
      </LegalSection>

      <LegalSection title="5. Email, alerts, and other providers">
        <p>
          Owner email alerts use the email address on the account and the
          configured SMTP service. The deployment template uses Hostinger SMTP
          when that integration is enabled. Slack, Discord, and generic webhook
          alerts are sent only to destinations that you configure and link to a
          monitor; those destination providers receive the alert payload.
        </p>
        <p>
          If paid billing is configured, Stripe handles checkout, customer
          records, subscription status, and the customer portal. Sitemyra stores
          the resulting customer and subscription identifiers and plan status;
          payment card details are not intended to be stored in the Sitemyra
          database. If Google or GitHub sign-in is enabled, those providers
          handle the sign-in flow. If S3-compatible artifact storage is enabled,
          the configured storage provider handles stored artifacts.
        </p>
        <p>
          These integrations are optional. Their availability depends on the
          deployment configuration and, where relevant, your own provider
          accounts.
        </p>
      </LegalSection>

      <LegalSection title="6. Weekly digest preferences">
        <p>
          Sitemyra currently schedules a weekly monitoring digest for active
          users who have at least one monitor. The digest contains monitor
          names, check counts, uptime, average latency, and price drift where
          available. It is separate from the change, failure, and recovery
          toggles, and users can turn it off in Account settings. No separate
          marketing-email list is currently used.
        </p>
      </LegalSection>

      <LegalSection title="7. Billing and subscription records">
        <p>
          When a paid plan is available, Sitemyra stores the plan name, status,
          monthly amount, current period information, Stripe customer
          identifier, Stripe subscription identifier, and cancellation state.
          The payment provider processes payment details according to its own
          terms. Do not send card numbers or payment credentials to Sitemyra
          support.
        </p>
      </LegalSection>

      <LegalSection title="8. Retention and deletion">
        <p>
          The current plan history windows are seven days for Free, thirty days
          for Pro, and ninety days for Business. Stored artifacts and checks
          are also subject to the configured artifact-retention cap, if one is
          set. Account and related records are retained while the account is
          active unless deleted or required to be retained for security, legal,
          or billing purposes.
        </p>
        <p>
          The current dashboard does not advertise a self-service account
          deletion control. To request deletion or export of account data,
          contact the founder through the <Link href="/contact">contact page</Link>.
          Backup retention at the hosting or infrastructure layer is not
          specified in this repository and should be confirmed by the operator.
        </p>
      </LegalSection>

      <LegalSection title="9. Cookies and browser storage">
        <p>
          The current marketing site and application do not use an advertising or
          analytics cookie. Authentication tokens are kept in browser
          <code> sessionStorage</code> so they are not persistent tracking
          cookies. The application also uses browser storage for the short-lived
          sign-in flow. See the <Link href="/cookies">Cookie Policy</Link> for
          the current browser-storage explanation.
        </p>
      </LegalSection>

      <LegalSection title="10. Your choices and rights">
        <p>
          Depending on where you live and the data-protection rules that apply,
          you may have rights to access, correct, export, delete, restrict, or
          object to certain processing, and to withdraw consent where consent
          is the basis used. You may also have the right to complain to a
          competent data-protection authority.
        </p>
        <p>
          Contact the founder to make a request. The operator may need to
          verify that the request comes from the account holder. The operator
          should not promise a response time until its legal and support process
          is finalized.
        </p>
      </LegalSection>

      <LegalSection title="11. International transfers and children">
        <p>
          Infrastructure, email, payment, sign-in, or storage providers may
          process information outside Greece. The operator should verify the
          relevant transfer safeguards and add provider-specific details before
          launch. Sitemyra is not directed to children, and the project does
          not knowingly collect information from children.
        </p>
      </LegalSection>

      <LegalSection title="12. Contact and policy changes">
        <p>
          Use the <Link href="/contact">contact page</Link> for privacy questions
          or requests. This policy may change as the product, providers, or
          business setup changes. Material changes should be posted here with an
          appropriate effective date after they are verified.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
