# Generated by Django 5.2.17 on 2026-09-26 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_subscription_billing_sub_status_0dd7b2_idx_and_more'),
        ('intelligence', '0003_organization_organizationmembership_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='intelligence.organization'),
        ),
    ]
