# Generated by Django 5.2.17 on 2026-09-20 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workspacemembership',
            new_name='workspaces__workspa_0c4683_idx',
            old_name='workspaces__workspa_4b8c6e_idx',
        ),
    ]
