# Generated by Django 5.2.17 on 2026-09-26 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0003_organization_organizationmembership_report_and_more'),
        ('workspaces', '0002_rename_workspaces__workspa_4b8c6e_idx_workspaces__workspa_0c4683_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_workspaces', to='intelligence.organization'),
        ),
    ]
