# Generated by Django 5.2.17 on 2026-09-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_workspace_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceinvite',
            name='email_error',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='workspaceinvite',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspaceinvite',
            name='email_status',
            field=models.CharField(choices=[('not_configured', 'Email not configured'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='not_configured', max_length=20),
        ),
    ]
