# Generated by Django 5.2.17 on 2026-09-19 12:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checked_at', models.DateTimeField()),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('changed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitors.monitor')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['monitor', '-checked_at'], name='monitors_mo_monitor_7dd5e8_idx'), models.Index(fields=['monitor', 'changed'], name='monitors_mo_monitor_73ee0d_idx')],
            },
        ),
    ]
