# Generated by Django 5.2.17 on 2026-09-20 11:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0002_monitorcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedMonitorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('http', 'HTTP'), ('dom', 'DOM'), ('screenshot', 'Screenshot'), ('price', 'Price')], default='http', max_length=20)),
                ('selector', models.TextField(blank=True, default='', help_text='Optional CSS selector limiting the monitored content.')),
                ('price_selector', models.TextField(blank=True, default='', help_text='CSS selector used by price monitors.')),
                ('price_currency', models.CharField(blank=True, default='', max_length=3)),
                ('screenshot_threshold', models.DecimalField(decimal_places=3, default=0.5, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_config', to='monitors.monitor')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeDiff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diff_type', models.CharField(choices=[('dom', 'DOM'), ('screenshot', 'Screenshot'), ('price', 'Price')], max_length=20)),
                ('summary', models.TextField(blank=True, default='')),
                ('diff_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('artifact_path', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_change_diffs', to='monitors.monitorcheck')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_diffs', to='monitors.monitor')),
                ('previous_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_change_diffs', to='monitors.monitorcheck')),
            ],
            options={
                'indexes': [models.Index(fields=['monitor', '-created_at'], name='monitors_ch_monitor_cf77bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='PricePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('raw_value', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_points', to='monitors.monitor')),
                ('monitor_check', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_point', to='monitors.monitorcheck')),
            ],
            options={
                'indexes': [models.Index(fields=['monitor', '-created_at'], name='monitors_pr_monitor_3d9894_idx')],
            },
        ),
    ]
