# Generated by Django 5.2.17 on 2026-09-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0004_workspace_and_intervals'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='monitorcheck',
            index=models.Index(fields=['checked_at'], name='monitors_mo_checked_5587c0_idx'),
        ),
    ]
