# Generated by Django 5.2.17 on 2026-09-26 09:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitors', '0005_monitorcheck_monitors_mo_checked_5587c0_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('brand', models.CharField(blank=True, default='', max_length=150)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('product_detected', models.BooleanField(default=False)),
                ('detection_note', models.CharField(blank=True, default='', max_length=300)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_watch', to='monitors.monitor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('captured_at', models.DateTimeField()),
                ('name', models.CharField(blank=True, default='', max_length=250)),
                ('brand', models.CharField(blank=True, default='', max_length=150)),
                ('sku', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('availability', models.CharField(blank=True, default='', max_length=40)),
                ('condition', models.CharField(blank=True, default='', max_length=60)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('review_count', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('badges', models.JSONField(blank=True, default=list)),
                ('variants', models.JSONField(blank=True, default=list)),
                ('images', models.JSONField(blank=True, default=list)),
                ('bundles', models.JSONField(blank=True, default=list)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('shipping', models.JSONField(blank=True, default=dict)),
                ('price_valid_until', models.CharField(blank=True, default='', max_length=60)),
                ('source_url', models.URLField(max_length=1000)),
                ('extraction', models.JSONField(blank=True, default=dict)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monitor_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_snapshots', to='monitors.monitorcheck')),
                ('product_watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='intelligence.productwatch')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=80)),
                ('before', models.TextField(blank=True, default='')),
                ('after', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('minor', 'Minor'), ('important', 'Important'), ('critical', 'Critical')], default='informational', max_length=20)),
                ('category', models.CharField(choices=[('pricing', 'Pricing'), ('product', 'Product'), ('features', 'Features'), ('availability', 'Availability'), ('content', 'Content'), ('reviews', 'Reviews'), ('marketing', 'Marketing')], default='content', max_length=20)),
                ('basis', models.TextField(blank=True, default='')),
                ('rule', models.CharField(blank=True, default='', max_length=40)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('source_url', models.URLField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monitor_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_changes', to='monitors.monitorcheck')),
                ('current_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_from', to='intelligence.productsnapshot')),
                ('previous_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_to', to='intelligence.productsnapshot')),
                ('product_watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='intelligence.productwatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UrlAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=1000)),
                ('normalized_url', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('ok', 'Analyzed'), ('failed', 'Failed')], default='ok', max_length=20)),
                ('page_kind', models.CharField(default='other', max_length=40)),
                ('classification_confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=10)),
                ('classification_rationale', models.TextField(blank=True, default='')),
                ('facts', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('product_detected', models.BooleanField(default=False)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('fetched_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveredTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=1000)),
                ('kind', models.CharField(default='other', max_length=40)),
                ('label', models.CharField(max_length=200)),
                ('why', models.TextField(blank=True, default='')),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('relevance', models.PositiveSmallIntegerField(default=0)),
                ('is_product', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='intelligence.urlanalysis')),
            ],
            options={
                'ordering': ['-is_primary', '-relevance', 'url'],
            },
        ),
        migrations.AddIndex(
            model_name='productwatch',
            index=models.Index(fields=['-updated_at'], name='intelligenc_updated_d21dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='productsnapshot',
            index=models.Index(fields=['product_watch', '-captured_at'], name='intelligenc_product_6aaace_idx'),
        ),
        migrations.AddIndex(
            model_name='productsnapshot',
            index=models.Index(fields=['captured_at'], name='intelligenc_capture_91d024_idx'),
        ),
        migrations.AddIndex(
            model_name='productchange',
            index=models.Index(fields=['product_watch', '-created_at'], name='intelligenc_product_741cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='productchange',
            index=models.Index(fields=['category', '-created_at'], name='intelligenc_categor_1d77ee_idx'),
        ),
        migrations.AddIndex(
            model_name='productchange',
            index=models.Index(fields=['severity', '-created_at'], name='intelligenc_severit_77a628_idx'),
        ),
        migrations.AddIndex(
            model_name='urlanalysis',
            index=models.Index(fields=['user', '-fetched_at'], name='intelligenc_user_id_c4a1fa_idx'),
        ),
        migrations.AddIndex(
            model_name='urlanalysis',
            index=models.Index(fields=['user', 'normalized_url'], name='intelligenc_user_id_951a44_idx'),
        ),
        migrations.AddIndex(
            model_name='urlanalysis',
            index=models.Index(fields=['expires_at'], name='intelligenc_expires_92b062_idx'),
        ),
        migrations.AddIndex(
            model_name='discoveredtarget',
            index=models.Index(fields=['analysis', '-relevance'], name='intelligenc_analysi_c0c9ff_idx'),
        ),
        migrations.AddIndex(
            model_name='discoveredtarget',
            index=models.Index(fields=['kind'], name='intelligenc_kind_b2b471_idx'),
        ),
        migrations.AddConstraint(
            model_name='discoveredtarget',
            constraint=models.UniqueConstraint(fields=('analysis', 'url'), name='unique_target_per_analysis'),
        ),
    ]
