# Generated by Django 5.2.17 on 2026-09-26 11:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
        ('monitors', '0005_monitorcheck_monitors_mo_checked_5587c0_idx'),
        ('workspaces', '0002_rename_workspaces__workspa_4b8c6e_idx_workspaces__workspa_0c4683_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('homepage_url', models.URLField(max_length=1000)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('relationship', models.CharField(choices=[('tracked', 'Tracked'), ('direct', 'Direct competitor'), ('adjacent', 'Adjacent competitor'), ('alternative', 'Alternative')], default='tracked', max_length=20)),
                ('relationship_reasons', models.JSONField(blank=True, default=list)),
                ('signals', models.JSONField(blank=True, default=list)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-last_activity_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=1000)),
                ('domain', models.CharField(max_length=255)),
                ('relationship', models.CharField(choices=[('tracked', 'Tracked'), ('direct', 'Direct competitor'), ('adjacent', 'Adjacent competitor'), ('alternative', 'Alternative')], default='adjacent', max_length=20)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='intelligence.competitor')),
            ],
            options={
                'ordering': ['-confidence', 'domain'],
            },
        ),
        migrations.CreateModel(
            name='MarketSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('price_increase_cluster', 'Several competitors increased prices'), ('price_decrease_cluster', 'Several competitors cut prices'), ('feature_parity', 'Several competitors shipped a similar capability'), ('feature_removal', 'A competitor removed a capability'), ('new_category', 'A competitor entered a new category'), ('new_product', 'A competitor published a new product page'), ('hiring_push', 'A competitor started hiring for a function')], max_length=40)),
                ('headline', models.CharField(max_length=300)),
                ('statement', models.TextField(blank=True, default='')),
                ('interpretation', models.TextField(blank=True, default='')),
                ('window_days', models.PositiveSmallIntegerField(default=30)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], default='new', max_length=20)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_signals', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_signals', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('pricing', 'Pricing'), ('products', 'Products'), ('features', 'Features'), ('marketing', 'Marketing'), ('content', 'Content'), ('hiring', 'Hiring'), ('other', 'Other')], default='other', max_length=20)),
                ('headline', models.CharField(max_length=300)),
                ('summary', models.TextField(blank=True, default='')),
                ('before', models.CharField(blank=True, default='', max_length=300)),
                ('after', models.CharField(blank=True, default='', max_length=300)),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('minor', 'Minor'), ('important', 'Important'), ('critical', 'Critical')], default='informational', max_length=20)),
                ('source_url', models.URLField(blank=True, default='', max_length=1000)),
                ('source_key', models.CharField(max_length=120, unique=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('detected_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signal_events', to='intelligence.competitor')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_events', to='monitors.monitor')),
                ('monitor_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signal_events', to='monitors.monitorcheck')),
                ('product_change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signal_events', to='intelligence.productchange')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_events', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signal_events', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-detected_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='competitor',
            index=models.Index(fields=['user', 'domain'], name='intelligenc_user_id_be9df6_idx'),
        ),
        migrations.AddIndex(
            model_name='competitor',
            index=models.Index(fields=['workspace', '-last_activity_at'], name='intelligenc_workspa_b3febe_idx'),
        ),
        migrations.AddIndex(
            model_name='competitor',
            index=models.Index(fields=['user', '-last_activity_at'], name='intelligenc_user_id_28362a_idx'),
        ),
        migrations.AddConstraint(
            model_name='competitor',
            constraint=models.UniqueConstraint(fields=('user', 'domain'), name='unique_competitor_per_user_domain'),
        ),
        migrations.AddIndex(
            model_name='competitorcandidate',
            index=models.Index(fields=['competitor', 'approved'], name='intelligenc_competi_52aff4_idx'),
        ),
        migrations.AddConstraint(
            model_name='competitorcandidate',
            constraint=models.UniqueConstraint(fields=('competitor', 'url'), name='unique_candidate_per_competitor_url'),
        ),
        migrations.AddIndex(
            model_name='marketsignal',
            index=models.Index(fields=['user', '-created_at'], name='intelligenc_user_id_6a4722_idx'),
        ),
        migrations.AddIndex(
            model_name='marketsignal',
            index=models.Index(fields=['user', 'status'], name='intelligenc_user_id_4ee79a_idx'),
        ),
        migrations.AddIndex(
            model_name='marketsignal',
            index=models.Index(fields=['workspace', '-created_at'], name='intelligenc_workspa_1ef5e2_idx'),
        ),
        migrations.AddIndex(
            model_name='signalevent',
            index=models.Index(fields=['user', '-detected_at'], name='intelligenc_user_id_049f86_idx'),
        ),
        migrations.AddIndex(
            model_name='signalevent',
            index=models.Index(fields=['user', 'kind', '-detected_at'], name='intelligenc_user_id_fd4e47_idx'),
        ),
        migrations.AddIndex(
            model_name='signalevent',
            index=models.Index(fields=['competitor', '-detected_at'], name='intelligenc_competi_a505aa_idx'),
        ),
        migrations.AddIndex(
            model_name='signalevent',
            index=models.Index(fields=['workspace', '-detected_at'], name='intelligenc_workspa_9b90f0_idx'),
        ),
        migrations.AddIndex(
            model_name='signalevent',
            index=models.Index(fields=['monitor', '-detected_at'], name='intelligenc_monitor_0968b0_idx'),
        ),
    ]
