# Generated by Django 5.2.17 on 2026-09-26 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_competitor_competitorcandidate_marketsignal_and_more'),
        ('workspaces', '0002_rename_workspaces__workspa_4b8c6e_idx_workspaces__workspa_0c4683_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('branding', models.JSONField(blank=True, default=dict)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('business', 'Business')], default='pro', max_length=20)),
                ('mrr_cents', models.PositiveIntegerField(default=0)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('analyst', 'Analyst'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='intelligence.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['organization', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('intelligence', 'Competitive intelligence'), ('battlecard', 'Battlecard')], default='intelligence', max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('competitor_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('formats', models.JSONField(blank=True, default=list)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('branding', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='intelligence.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_reports', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_reports', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Battlecard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sections', models.JSONField(blank=True, default=dict)),
                ('positioning', models.TextField(blank=True, default='')),
                ('sources', models.JSONField(blank=True, default=list)),
                ('source_event_ids', models.JSONField(blank=True, default=list)),
                ('fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battlecard', to='intelligence.competitor')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['-generated_at'], name='intelligenc_generat_cf0734_idx')],
            },
        ),
        migrations.CreateModel(
            name='BrowserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(default='Browser extension', max_length=120)),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('prefix', models.CharField(max_length=20)),
                ('scopes', models.CharField(default='monitors:read monitors:write', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browser_sessions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='browser_sessions', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='intelligenc_user_id_d7bd53_idx'), models.Index(fields=['expires_at'], name='intelligenc_expires_efce17_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChangeExplanation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('what_changed', models.TextField(blank=True, default='')),
                ('why_it_may_matter', models.TextField(blank=True, default='')),
                ('what_to_check', models.TextField(blank=True, default='')),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('basis', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('model', models.CharField(blank=True, default='rules', max_length=60)),
                ('is_fallback', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signal_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='intelligence.signalevent')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['signal_event', '-created_at'], name='intelligenc_signal__982ab3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['owner'], name='intelligenc_owner_i_910919_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['-created_at'], name='intelligenc_created_cba76c_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['organization', 'role'], name='intelligenc_organiz_f16ec0_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['user'], name='intelligenc_user_id_334cb8_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='unique_organization_member'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['user', '-created_at'], name='intelligenc_user_id_494986_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['workspace', '-created_at'], name='intelligenc_workspa_73cd36_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['organization', '-created_at'], name='intelligenc_organiz_44d6f1_idx'),
        ),
    ]
