"""Exporters.

Seven formats, no new runtime dependency:

  csv      — the workhorse; source URL + timestamp on every row
  xlsx     — a real Office Open XML workbook, written with stdlib zipfile
  json     — full fidelity, the API's own shape
  markdown — paste-ready for a client deck or a Slack thread
  html     — a self-contained, printable, white-label-ready document
  xml      — for a CRM or an aggregator
  pdf      — via the reportlab dependency the compliance export already
             uses, with the same hand-rolled fallback when it is absent

**Every exporter is evidence-first.** `source_url` and `detected_at` are on
every row, so a downloaded file is self-auditing: a reader can always trace
a claim back to the page it came from. Nothing is summarised in a way that
loses the before/after pair.
"""

import csv
import io
import json
import zipfile
from datetime import datetime, timezone as dt_timezone
from html import escape
from xml.sax.saxutils import escape as xml_escape

from .product_diff import SEVERITY_LABELS

# Column order is the exporter's contract for csv/xlsx/xml.
COLUMNS = [
    ("detected_at", "Detected at"),
    ("competitor", "Competitor"),
    ("kind", "Category"),
    ("severity", "Severity"),
    ("headline", "What changed"),
    ("before", "Before"),
    ("after", "After"),
    ("rule", "Classification rule"),
    ("basis", "Why"),
    ("source_url", "Source URL"),
    ("monitor_name", "Monitor"),
    ("monitor_url", "Monitor URL"),
    ("signal_event_id", "Event id"),
    ("evidence", "Evidence"),
]

GENERATED_NOTE = (
    "Generated by Sitemyra from publicly accessible web pages. Every row "
    "carries its source URL and detection time so the claim can be checked. "
    "Sitemyra reports what a page published; it does not know a competitor's "
    "revenue, customers or intent."
)


def flatten_event(event) -> dict:
    competitor = getattr(event, "competitor", None)
    monitor = getattr(event, "monitor", None)
    evidence = event.evidence or {}
    return {
        "detected_at": event.detected_at.isoformat() if event.detected_at else "",
        "competitor": competitor.name if competitor else "",
        "kind": event.kind,
        "severity": SEVERITY_LABELS.get(event.severity, event.severity),
        "headline": event.headline,
        "before": event.before,
        "after": event.after,
        "rule": evidence.get("rule", ""),
        "basis": evidence.get("basis", "") or event.summary,
        "source_url": event.source_url,
        "monitor_name": monitor.name if monitor else "",
        "monitor_url": monitor.url if monitor else "",
        "signal_event_id": str(event.id),
        "evidence": json.dumps(evidence, sort_keys=True)[:500] if evidence else "",
    }


def flatten_competitor(competitor) -> dict:
    return {
        "detected_at": competitor.last_activity_at.isoformat()
        if competitor.last_activity_at
        else "",
        "competitor": competitor.name,
        "kind": "competitor",
        "severity": "",
        "headline": f"{competitor.relationship}: {competitor.homepage_url}",
        "before": "",
        "after": "",
        "rule": "",
        "basis": "; ".join(competitor.relationship_reasons or []),
        "source_url": competitor.homepage_url,
        "monitor_name": "",
        "monitor_url": "",
        "signal_event_id": "",
        "evidence": json.dumps({"signals": competitor.signals or []}, sort_keys=True)[:500],
    }


def rows_from(events=(), competitors=()):
    rows = [flatten_competitor(item) for item in competitors]
    rows.extend(flatten_event(item) for item in events)
    rows.sort(key=lambda row: row["detected_at"], reverse=True)
    return rows


# --------------------------------------------------------------------------
# CSV
# --------------------------------------------------------------------------


def to_csv(rows) -> bytes:
    buffer = io.StringIO()
    writer = csv.DictWriter(
        buffer, fieldnames=[key for key, _label in COLUMNS], extrasaction="ignore"
    )
    writer.writeheader()
    for row in rows:
        writer.writerow({key: row.get(key, "") for key, _label in COLUMNS})
    buffer.write("\n")
    buffer.write(f"# {GENERATED_NOTE}\n")
    return buffer.getvalue().encode("utf-8")


# --------------------------------------------------------------------------
# XLSX (Office Open XML, stdlib only)
# --------------------------------------------------------------------------

_XLSX_CONTENT_TYPES = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
<Default Extension="xml" ContentType="application/xml"/>
<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
<Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
<Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>
</Types>"""

_XLSX_RELS = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
</Relationships>"""

_XLSX_WORKBOOK = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
<sheets><sheet name="Intelligence" sheetId="1" r:id="rId1"/></sheets>
</workbook>"""

_XLSX_WORKBOOK_RELS = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>
<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
</Relationships>"""

_XLSX_STYLES = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
<fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="11"/><name val="Calibri"/></font></fonts>
<fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills>
<borders count="1"><border/></borders>
<cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs>
<cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="0" borderId="0" xfId="0" applyFont="1"/></cellXfs>
</styleSheet>"""

_MAX_XLSX_ROWS = 50000
_MAX_XLSX_CELL = 32000


def _column_name(index: int) -> str:
    name = ""
    index += 1
    while index:
        index, remainder = divmod(index - 1, 26)
        name = chr(65 + remainder) + name
    return name


def _xlsx_cell(reference: str, value, style: int = 0) -> str:
    style_attr = f' s="{style}"' if style else ""
    if value is None or value == "":
        return f'<c r="{reference}"{style_attr}/>'
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return f'<c r="{reference}"{style_attr}><v>{value}</v></c>'
    text = str(value)
    if len(text) > _MAX_XLSX_CELL:
        text = text[:_MAX_XLSX_CELL]
    return (
        f'<c r="{reference}" t="inlineStr"{style_attr}><is><t xml:space="preserve">'
        f"{escape(text)}</t></is></c>"
    )


def to_xlsx(rows, sheet_name="Intelligence") -> bytes:
    """A valid single-sheet .xlsx built with zipfile + XML only.

    Excel, Numbers, LibreOffice and Google Sheets all open this. Written by
    hand rather than pulling in openpyxl: a workbook writer is ~100 lines
    and a new dependency is a permanent supply-chain surface.
    """
    sheet_rows = []
    header_cells = "".join(
        _xlsx_cell(f"{_column_name(index)}1", label, style=1)
        for index, (_key, label) in enumerate(COLUMNS)
    )
    sheet_rows.append(f'<row r="1">{header_cells}</row>')
    for offset, row in enumerate(rows[:_MAX_XLSX_ROWS], start=2):
        cells = "".join(
            _xlsx_cell(f"{_column_name(index)}{offset}", row.get(key, ""))
            for index, (key, _label) in enumerate(COLUMNS)
        )
        sheet_rows.append(f'<row r="{offset}">{cells}</row>')
    truncated = (
        f'<row r="{len(rows[:_MAX_XLSX_ROWS]) + 2}">'
        f'<c r="A{len(rows[:_MAX_XLSX_ROWS]) + 2}" t="inlineStr"><is><t>'
        f"{escape(GENERATED_NOTE)}</t></is></c></row>"
        if len(rows) > _MAX_XLSX_ROWS
        else ""
    )
    sheet_xml = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
        "<sheetData>" + "".join(sheet_rows) + truncated + "</sheetData></worksheet>"
    )

    safe_sheet = escape(sheet_name)[:31]
    workbook_xml = _XLSX_WORKBOOK.replace(
        'name="Intelligence"', f'name="{safe_sheet}"'
    )

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        # Fixed timestamps keep the output byte-stable for the same input.
        info = zipfile.ZipInfo("[Content_Types].xml", date_time=(1980, 1, 1, 0, 0, 0))
        archive.writestr(info, _XLSX_CONTENT_TYPES)
        for name, content in (
            ("_rels/.rels", _XLSX_RELS),
            ("xl/workbook.xml", workbook_xml),
            ("xl/_rels/workbook.xml.rels", _XLSX_WORKBOOK_RELS),
            ("xl/styles.xml", _XLSX_STYLES),
            ("xl/worksheets/sheet1.xml", sheet_xml),
        ):
            entry = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
            archive.writestr(entry, content)
    return buffer.getvalue()


# --------------------------------------------------------------------------
# JSON
# --------------------------------------------------------------------------


def to_json(rows, meta=None) -> bytes:
    payload = {
        "generated_at": datetime.now(dt_timezone.utc).isoformat(),
        "note": GENERATED_NOTE,
        "columns": [{"key": key, "label": label} for key, label in COLUMNS],
        "meta": meta or {},
        "rows": rows,
    }
    return json.dumps(payload, indent=2, sort_keys=False, default=str).encode("utf-8")


# --------------------------------------------------------------------------
# Markdown
# --------------------------------------------------------------------------


def to_markdown(rows, title="Competitive intelligence export", meta=None) -> bytes:
    lines = [f"# {title}", ""]
    generated = datetime.now(dt_timezone.utc)
    lines.append(f"Generated {generated.strftime('%Y-%m-%d %H:%M UTC')}")
    if meta:
        for key in sorted(meta):
            if meta[key] not in (None, "", [], {}):
                lines.append(f"- {key.replace('_', ' ').title()}: {meta[key]}")
    lines.extend(["", f"_{GENERATED_NOTE}_", ""])
    if not rows:
        lines.append("_No changes were recorded for this selection._")
        return "\n".join(lines).encode("utf-8")

    lines.append(f"**{len(rows)} change(s)**")
    lines.append("")
    for row in rows:
        when = (row.get("detected_at") or "")[:16].replace("T", " ")
        lines.append(f"### {row.get('competitor') or 'Unknown'} — {row.get('headline') or ''}")
        lines.append("")
        lines.append(f"- **Detected:** {when} UTC")
        lines.append(f"- **Category:** {row.get('kind') or '—'} · **Severity:** {row.get('severity') or '—'}")
        if row.get("before") or row.get("after"):
            lines.append(f"- **Before:** {row.get('before') or '—'}")
            lines.append(f"- **After:** {row.get('after') or '—'}")
        if row.get("basis"):
            lines.append(f"- **Why:** {row['basis']}")
        if row.get("rule"):
            lines.append(f"- **Rule:** `{row['rule']}`")
        if row.get("source_url"):
            lines.append(f"- **Source:** {row['source_url']}")
        lines.append("")
    return "\n".join(lines).encode("utf-8")


# --------------------------------------------------------------------------
# HTML
# --------------------------------------------------------------------------

_BRAND_DEFAULT = {
    "agency_name": "Sitemyra",
    "tagline": "Competitive intelligence",
    "primary_color": "#0052ff",
    "footer": "",
    "show_sitemyra_credit": True,
}


def to_html(rows, title="Competitive intelligence report", meta=None, branding=None) -> bytes:
    brand = dict(_BRAND_DEFAULT)
    brand.update(branding or {})
    accent = escape(str(brand.get("primary_color") or "#0052ff"))
    parts = [
        "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">",
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        f"<title>{escape(title)}</title><style>",
        "body{font:15px/1.6 -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;",
        "color:#0f172a;background:#fff;margin:0;padding:40px 24px}",
        ".wrap{max-width:900px;margin:0 auto}",
        f"h1{{font-size:28px;margin:0 0 4px}}h2{{font-size:18px;margin:0 0 4px}}",
        ".muted{color:#64748b;font-size:13px}",
        f"table{{width:100%;border-collapse:collapse;margin-top:24px;font-size:13px}}",
        "th,td{text-align:left;padding:9px 10px;border-bottom:1px solid #e2e8f0;vertical-align:top}",
        "th{background:#f8fafc;font-weight:600;white-space:nowrap}",
        f"a{{color:{accent}}}code{{background:#f1f5f9;padding:1px 5px;border-radius:4px;font-size:12px}}",
        ".pill{display:inline-block;padding:2px 8px;border-radius:999px;background:#f1f5f9;font-size:11px}",
        ".note{margin-top:28px;padding:14px 16px;background:#f8fafc;border-radius:12px;font-size:12px;color:#475569}",
        "@media print{body{padding:0}}",
        "</style></head><body><div class=\"wrap\">",
        f'<p class="pill" style="background:{accent}1a;color:{accent}">{escape(str(brand.get("tagline") or ""))}</p>',
        f"<h1>{escape(title)}</h1>",
        f'<p class="muted">{escape(str(brand.get("agency_name") or "Sitemyra"))} · generated '
        f'{datetime.now(dt_timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}</p>',
    ]
    if meta:
        parts.append("<p class=\"muted\">")
        for key in sorted(meta):
            if meta[key] not in (None, "", [], {}):
                parts.append(
                    f"<br>{escape(str(key.replace('_', ' ').title()))}: "
                    f"{escape(str(meta[key]))}"
                )
        parts.append("</p>")

    if not rows:
        parts.append("<p class=\"muted\">No changes were recorded for this selection.</p>")
    else:
        parts.append(f"<p class=\"muted\">{len(rows)} change(s)</p><table><thead><tr>")
        parts.append(
            "<th>Detected</th><th>Competitor</th><th>Category</th>"
            "<th>What changed</th><th>Before</th><th>After</th><th>Source</th></tr></thead><tbody>"
        )
        for row in rows:
            when = escape((row.get("detected_at") or "")[:19].replace("T", " "))
            source = row.get("source_url") or ""
            source_cell = (
                f'<a href="{escape(source)}">{escape(source[:60])}</a>' if source else "—"
            )
            parts.append(
                "<tr>"
                f"<td>{when}</td>"
                f"<td>{escape(str(row.get('competitor') or '—'))}</td>"
                f"<td>{escape(str(row.get('kind') or '—'))}</td>"
                f"<td>{escape(str(row.get('headline') or '—'))}"
                + (
                    f"<br><span class=\"muted\">{escape(str(row.get('basis'))[:160])}</span>"
                    if row.get("basis")
                    else ""
                )
                + "</td>"
                f"<td>{escape(str(row.get('before') or '—'))}</td>"
                f"<td>{escape(str(row.get('after') or '—'))}</td>"
                f"<td>{source_cell}</td>"
                "</tr>"
            )
        parts.append("</tbody></table>")

    parts.append(f'<p class="note">{escape(GENERATED_NOTE)}</p>')
    if brand.get("show_sitemyra_credit"):
        parts.append(
            '<p class="muted" style="margin-top:18px">Generated with Sitemyra.</p>'
        )
    if brand.get("footer"):
        parts.append(f'<p class="muted">{escape(str(brand["footer"]))}</p>')
    parts.append("</div></body></html>")
    return "".join(parts).encode("utf-8")


# --------------------------------------------------------------------------
# XML
# --------------------------------------------------------------------------


def to_xml(rows, meta=None) -> bytes:
    parts = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<sitemyra-intelligence xmlns="https://sitemyra.com/schema/intelligence/1" version="1">',
        f"<generated-at>{datetime.now(dt_timezone.utc).isoformat()}</generated-at>",
        f"<note>{xml_escape(GENERATED_NOTE)}</note>",
    ]
    if meta:
        parts.append("<meta>")
        for key in sorted(meta):
            parts.append(
                f"<{key}>{xml_escape(str(meta[key]))}</{key}>"
            )
        parts.append("</meta>")
    parts.append(f'<change-count>{len(rows)}</change-count>')
    parts.append("<changes>")
    for row in rows:
        parts.append("<change>")
        for key, _label in COLUMNS:
            value = row.get(key, "")
            parts.append(f"<{key}>{xml_escape(str(value))}</{key}>")
        parts.append("</change>")
    parts.append("</changes></sitemyra-intelligence>")
    return "".join(parts).encode("utf-8")


# --------------------------------------------------------------------------
# PDF (reportlab, with the compliance export's hand-rolled fallback)
# --------------------------------------------------------------------------


def to_pdf(rows, title="Competitive intelligence report", meta=None) -> bytes:
    try:
        from reportlab.lib.pagesizes import landscape, letter
        from reportlab.pdfgen import canvas
    except ImportError:
        return _fallback_pdf(rows, title)

    try:
        buffer = io.BytesIO()
        page_size = landscape(letter) if len(COLUMNS) > 4 else letter
        pdf = canvas.Canvas(buffer, pagesize=page_size)
        width, height = page_size
        y = height - 46
        pdf.setFont("Helvetica-Bold", 15)
        pdf.drawString(36, y, title[:110])
        y -= 15
        pdf.setFont("Helvetica", 8)
        pdf.drawString(
            36, y, f"Generated {datetime.now(dt_timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} UTC  |  {len(rows)} change(s)"
        )
        y -= 12
        pdf.drawString(36, y, "Every row carries its source URL and detection time.")
        y -= 18

        def ensure(needed=12):
            nonlocal y
            if y < 50 + needed:
                pdf.showPage()
                y = height - 46

        pdf.setFont("Helvetica-Bold", 7)
        columns = [
            ("Detected", 76), ("Competitor", 78), ("Cat", 48), ("What changed", 168),
            ("Before", 76), ("After", 76), ("Source", 150),
        ]
        x = 36
        for label, span in columns:
            pdf.drawString(x, y, label)
            x += span
        y -= 6
        pdf.line(36, y, width - 36, y)
        y -= 10

        pdf.setFont("Helvetica", 7)
        for row in rows[:2000]:
            ensure(20)
            values = [
                (row.get("detected_at") or "")[:19].replace("T", " "),
                (row.get("competitor") or "")[:18],
                (row.get("kind") or "")[:10],
                (row.get("headline") or "")[:40],
                (row.get("before") or "")[:18],
                (row.get("after") or "")[:18],
                (row.get("source_url") or "")[:44],
            ]
            x = 36
            for (value, (_label, span)) in zip(values, columns):
                if value:
                    pdf.drawString(x, y, str(value))
                x += span
            y -= 9
            source = row.get("source_url") or ""
            if source:
                pdf.setFont("Helvetica", 6)
                ensure(8)
                pdf.drawString(44, y, f"rule={row.get('rule') or '-'}  {source[:120]}")
                pdf.setFont("Helvetica", 7)
                y -= 9
            y -= 2
        ensure(30)
        pdf.setFont("Helvetica-Oblique", 6)
        for line in _wrap(GENERATED_NOTE, 150):
            pdf.drawString(36, y, line)
            y -= 8
        pdf.save()
        return buffer.getvalue()
    except Exception:
        return _fallback_pdf(rows, title)


def _wrap(text, width):
    words = str(text).split()
    lines, current = [], ""
    for word in words:
        if len(current) + len(word) + 1 > width:
            lines.append(current)
            current = word
        else:
            current = f"{current} {word}".strip()
    if current:
        lines.append(current)
    return lines


def _fallback_pdf(rows, title):
    """A minimal but valid PDF, so the endpoint works without reportlab.

    Same approach as the existing compliance export: never fail a download
    because an optional library is missing.
    """
    lines = [title[:110], f"Generated {datetime.now(dt_timezone.utc).isoformat()}", ""]
    for row in rows[:400]:
        lines.append(
            f"{(row.get('detected_at') or '')[:19]}  {row.get('competitor') or ''}  "
            f"{row.get('kind') or ''}  {row.get('headline') or ''}"
        )
        if row.get("before") or row.get("after"):
            lines.append(f"    before: {row.get('before') or '-'}   after: {row.get('after') or '-'}")
        if row.get("source_url"):
            lines.append(f"    source: {row['source_url'][:100]}")
    lines.extend(["", GENERATED_NOTE])
    text = "\n".join(lines)
    escaped = text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
    content = f"BT /F1 9 Tf 36 750 Td ({escaped}) Tj ET"
    return (
        "%PDF-1.4\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n"
        "2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n"
        "3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 792 612]/Contents 4 0 R>>endobj\n"
        f"4 0 obj<</Length {len(content)}>>stream\n{content}\nendstream\nendobj\n"
        "trailer<</Root 1 0 R>>\n%%EOF"
    ).encode("latin-1", errors="replace")


# --------------------------------------------------------------------------
# Dispatch
# --------------------------------------------------------------------------

FORMATS = {
    "csv": ("text/csv", "csv"),
    "xlsx": (
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "xlsx",
    ),
    "json": ("application/json", "json"),
    "markdown": ("text/markdown; charset=utf-8", "md"),
    "md": ("text/markdown; charset=utf-8", "md"),
    "html": ("text/html; charset=utf-8", "html"),
    "xml": ("application/xml", "xml"),
    "pdf": ("application/pdf", "pdf"),
}


def render(fmt: str, rows, title="Competitive intelligence export", meta=None, branding=None, sheet_name="Intelligence") -> bytes:
    key = (fmt or "csv").strip().lower()
    if key == "csv":
        return to_csv(rows)
    if key == "xlsx":
        return to_xlsx(rows, sheet_name=sheet_name)
    if key == "json":
        return to_json(rows, meta)
    if key in ("markdown", "md"):
        return to_markdown(rows, title=title, meta=meta)
    if key == "html":
        return to_html(rows, title=title, meta=meta, branding=branding)
    if key == "xml":
        return to_xml(rows, meta)
    if key == "pdf":
        return to_pdf(rows, title=title, meta=meta)
    raise ValueError(f"unsupported export format: {fmt}")
